import Head from 'next/head'
import Image from 'next/image'
import { Heebo } from '@next/font/google'
import User from '@/components/User'
import HomeStyle from '@/styles/home.module.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>


      <div className={HomeStyle.home}>
        <User />
      </div>

    </>
  )
}
